// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnfoezbfjglhvfltbwhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZm9lemJmamdsaHZmbHRid2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzYzNTEsImV4cCI6MjA2NDkxMjM1MX0.8g9mWcvvYCX2ISJdkU6KWZh8iMQDvUSQcP7LTGuh4Ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);